services:
#    api.example:
#        class: APIBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    api.secureapi:
        class: APIBundle\ToolsNombre\SecuriteAPI
        
    api.secureapi.listener:
       class: APIBundle\ToolsNombre\SecuriteAPIListener
       arguments: ["@api.secureapi"]
       tags:
           - { name: kernel.event_listener, event: kernel.controller, method: processSecure }
            
            
           
           
    api.generernombre:
        class: APIBundle\ToolsNombre\GenererNombre
        arguments: ["@service_container"]